/* V8 — CATÁLOGO independente da Loja */
const catalogState = { projectId:"", products:[], categories:[] };
async function renderCatalogSection(){
  const el=$("catalog-content"); if(!el)return; const projects=state.projects||[];
  if(!projects.length){el.innerHTML='<div class="empty-state">Nenhum projeto cadastrado.</div>';return;}
  if(!catalogState.projectId || !projects.some(p=>p.id===catalogState.projectId)) catalogState.projectId=projects[0].id;
  await loadCatalog();
  el.innerHTML=`<div class="module-head"><div><p class="eyebrow">V8 UNIVERSAL</p><h1>Catálogo</h1><p>Produtos, serviços, combos, pacotes e planos. Independente da Loja.</p></div><div class="module-actions"><select id="catalog-project">${projects.map(p=>`<option value="${escapeHtml(p.id)}" ${p.id===catalogState.projectId?'selected':''}>${escapeHtml(p.name||'Projeto')}</option>`).join('')}</select><button class="btn btn-primary" onclick="openCatalogItem()">+ Adicionar item</button></div></div><div class="module-toolbar"><input id="catalog-search" placeholder="Buscar no catálogo..." oninput="paintCatalog()"><select id="catalog-type" onchange="paintCatalog()"><option value="">Todos os tipos</option><option value="product">Produto</option><option value="service">Serviço</option><option value="combo">Combo</option><option value="package">Pacote</option><option value="plan">Plano</option><option value="other">Outro</option></select><select id="catalog-status" onchange="paintCatalog()"><option value="">Todos os status</option><option value="active">Ativos</option><option value="inactive">Inativos</option></select></div><div id="catalog-list"></div>`;
  $("#catalog-project").onchange=async e=>{catalogState.projectId=e.target.value;await loadCatalog();paintCatalog();}; paintCatalog();
}
async function loadCatalog(){const r=await API.get(`/api/data/catalog/${encodeURIComponent(catalogState.projectId)}`);catalogState.products=r?.products||[];catalogState.categories=r?.categories||[];}
function paintCatalog(){const el=$("#catalog-list");if(!el)return;const q=($("#catalog-search")?.value||'').toLowerCase();const t=$("#catalog-type")?.value||'';const st=$("#catalog-status")?.value||'';const list=catalogState.products.filter(p=>(!q||`${p.name} ${p.description}`.toLowerCase().includes(q))&&(!t||p.itemType===t)&&(!st||p.status===st));el.innerHTML=list.length?`<div class="catalog-grid">${list.map(p=>`<article class="catalog-card"><div class="catalog-card-media">${p.image?`<img src="${escapeHtml(p.image)}" alt="">`:'◈'}</div><div class="catalog-card-body"><div class="catalog-tags"><span class="badge badge-muted">${escapeHtml(p.itemType||'product')}</span>${p.featured?'<span class="badge badge-success">Destaque</span>':''}${p.promotion?'<span class="badge">Promoção</span>':''}</div><h3>${escapeHtml(p.name)}</h3><p>${escapeHtml(p.description||'')}</p><strong>${p.price==null?'Sob consulta':formatMoney(p.price)}</strong></div><div class="catalog-card-actions"><button class="btn btn-sm" onclick="openCatalogItem('${escapeHtml(p.id)}')">Editar</button><button class="btn btn-sm btn-danger" onclick="deleteCatalogItem('${escapeHtml(p.id)}')">Excluir</button></div></article>`).join('')}</div>`:`<div class="empty-state"><strong>Nenhum item encontrado</strong><p>Use os filtros ou adicione um item ao catálogo.</p></div>`;}
function openCatalogItem(id=null){const p=id?catalogState.products.find(x=>x.id===id):null;const overlay=document.createElement('div');overlay.className='modal-overlay';overlay.id='catalog-editor';overlay.innerHTML=`<div class="modal universal-modal"><button class="modal-close" onclick="closeCatalogItem()">×</button><div class="modal-max-row"><span>Item do catálogo</span><button class="btn btn-sm" onclick="this.closest('.modal').classList.toggle('modal-maximized')">□ Maximizar</button></div><h2>${p?'Editar item':'Adicionar item'}</h2><label>Nome<input id="cat-name" value="${escapeHtml(p?.name||'')}"></label><label>Tipo<select id="cat-type-edit">${[['product','Produto'],['service','Serviço'],['combo','Combo'],['package','Pacote'],['plan','Plano'],['other','Outro']].map(([v,l])=>`<option value="${v}" ${p?.itemType===v?'selected':''}>${l}</option>`).join('')}</select></label><label>Descrição<textarea id="cat-desc" rows="4">${escapeHtml(p?.description||'')}</textarea></label><div class="form-grid-2"><label>Preço<input id="cat-price" type="number" min="0" step="0.01" value="${p?.price??''}" placeholder="Deixe vazio para 'sob consulta'"></label><label>Peso (kg)<input id="cat-weight" type="number" min="0" step="0.01" value="${p?.weight??0}"></label></div><label>Categoria<select id="cat-category"><option value="">Sem categoria</option>${catalogState.categories.map(c=>`<option value="${escapeHtml(c.id)}" ${p?.categoryId===c.id?'selected':''}>${escapeHtml(c.name)}</option>`).join('')}</select></label><label>Imagem<input id="cat-image" value="${escapeHtml(p?.image||'')}" placeholder="URL da imagem"></label><div class="form-grid-2"><label class="check-row"><input id="cat-featured" type="checkbox" ${p?.featured?'checked':''}> Destaque</label><label class="check-row"><input id="cat-promo" type="checkbox" ${p?.promotion?'checked':''}> Promoção</label></div><label>Status<select id="cat-status-edit"><option value="active" ${p?.status!=='inactive'?'selected':''}>Ativo</option><option value="inactive" ${p?.status==='inactive'?'selected':''}>Inativo</option></select></label><div class="modal-actions modal-save-bar"><button class="btn" onclick="closeCatalogItem()">Cancelar</button><button class="btn btn-primary modal-save-floating" onclick="saveCatalogItem('${escapeHtml(id||'')}')">Salvar</button></div></div>`;document.body.appendChild(overlay);}
function closeCatalogItem(){$('#catalog-editor')?.remove();}
async function saveCatalogItem(id){const body={name:$('#cat-name').value.trim(),description:$('#cat-desc').value.trim(),itemType:$('#cat-type-edit').value,price:$('#cat-price').value===''?null:Number($('#cat-price').value),weight:Number($('#cat-weight').value||0),categoryId:$('#cat-category').value,image:$('#cat-image').value.trim(),featured:$('#cat-featured').checked,promotion:$('#cat-promo').checked,status:$('#cat-status-edit').value,trackStock:false,stock:0};if(!body.name)return toast('Informe o nome.','error');const url=id?`/api/data/products/${encodeURIComponent(catalogState.projectId)}/${encodeURIComponent(id)}`:`/api/data/products/${encodeURIComponent(catalogState.projectId)}`;const r=id?await API.put(url,body):await API.post(url,body);if(r?.error||r?.success===false)return toast(r?.error||'Erro ao salvar.','error');closeCatalogItem();await loadCatalog();paintCatalog();toast(id?'Item atualizado.':'Item adicionado.');}
async function deleteCatalogItem(id){if(!confirm('Excluir este item do catálogo?'))return;const r=await API.del(`/api/data/products/${encodeURIComponent(catalogState.projectId)}/${encodeURIComponent(id)}`);if(r?.error||r?.success===false)return toast(r?.error||'Erro ao excluir.','error');await loadCatalog();paintCatalog();toast('Item excluído.');}
window.renderCatalogSection=renderCatalogSection;window.openCatalogItem=openCatalogItem;window.closeCatalogItem=closeCatalogItem;window.saveCatalogItem=saveCatalogItem;window.deleteCatalogItem=deleteCatalogItem;
