name = "v8adminuniversal"
main = "index.js"
compatibility_date = "2024-11-01"

[[kv_namespaces]]
binding = "V8_KV"
id = "48cb4e4cd5354c648a48d120fe87951f"

[[d1_databases]]
binding = "V8_D1"
database_name = "v8adminuniversal-db"
database_id = "caf750f5-73dc-4d46-8938-7e82818ceea0"

# R2 será configurado futuramente.

# Secrets (NÃO ficam neste arquivo — configure com):
#   wrangler secret put ADMIN_EMAIL
#   wrangler secret put ADMIN_PASS
#   wrangler secret put TOKEN_SECRET
#   wrangler secret put GOOGLE_PLACES_API_KEY
